name: Keep Render Warm

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Render health endpoint
        env:
          PING_URL: ${{ secrets.RENDER_PING_URL }}
          DEFAULT_PING_URL: https://physical-therapy-api.onrender.com/health/db
        run: |
          URL="${PING_URL:-$DEFAULT_PING_URL}"
          echo "Pinging $URL"
          curl --fail --silent --show-error "$URL" > /dev/null || echo "Ping failed but continuing."